# general settings
name: 060_Flowformer_1016_CL_RoPE_2to10_d128c64f512_1k_proto64_b4_t0.1
model_type: CLModel
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: JHT2025Pre_mix2to10
    type: DeinterleavingDataset
    dataroot: D:/Datasets/JHT2025Pre/train1016
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 30
    prefetch_mode: cuda
    pin_memory: true
    use_flip: false

  val:
    name: JHT2025Pre_mix2to10
    type: DeinterleavingDataset
    dataroot: D:/Datasets/JHT2025Pre/val1016
    io_backend:
      type: disk

# network structures
network_g:
  type: Flowformer_P
  seq_len: 1000
  enc_in: 4
  d_model: 128
  c_out: 64
  n_heads: 8
  d_ff: 512
  activation: relu
  dropout: 0.1
  e_layers: 8
  pe_mode: RoPE
  label_num: 15
  prototype_num: 64

#network_g:
#  type: SimpleMLP
#  seq_len: 3000
#  c_in: 5
#  c_out: 32
#  d_model: 256

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state:  ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: !!float 1e-7
    betas: [0.9, 0.99]

  scheduler:
#    type: CosineAnnealingRestartLR
#    periods: [100000, 100000, 100000, 100000]
#    restart_weights: [1, 0.5, 0.5, 0.5]
#    eta_min: !!float 1e-6
    type: MultiStepLR
    milestones: [100000, 200000, 300000]
    gamma: 0.5

  # sample_milestone: 150000

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  infonce_opt:
    type: InfoNCELoss
    loss_weight: 1.0
    temperature: 0.1
    reduction: mean

### validation settings
val:
  val_freq: !!float 2e4
  save_img:
    enable: true
    save_label: true
    save_pdwimg: false
    save_featureTSNE: true

  metrics:
    ac: # metric name, can be arbitrary
      type: calculate_ac
    nmi:
      type: calculate_nmi
    ari:
      type: calculate_ari

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
