# general settings
name: 023_Deinterleaving_Flowformer_CL_RoPE_2to10_1k_allNeg_noTOA_LossImpl3_PointSeg_wsl
model_type: CLModel
num_gpu: 2
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: JHT2025Pre_mix2to10
    type: DeinterleavingDataset
    dataroot: /mnt/d/Datasets/JHT2025Pre/train1016
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~
    # pin_memory: true

    use_flip: true

  val:
    name: JHT2025Pre_mix2to10
    type: DeinterleavingDataset
    dataroot: /mnt/d/Datasets/JHT2025Pre/val1016
    io_backend:
      type: disk

# network structures
network_g:
  type: Flowformer
  seq_len: 1000
  enc_in: 4
  d_model: 128
  c_out: 32
  n_heads: 8
  d_ff: 512
  activation: relu
  dropout: 0.1
  e_layers: 8
  pe_mode: RoPE

#network_g:
#  type: SimpleMLP
#  seq_len: 3000
#  c_in: 5
#  c_out: 32
#  d_model: 256

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state:  ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: !!float 1e-5
    betas: [0.9, 0.99]

  scheduler:
#    type: CosineAnnealingRestartLR
#    periods: [100000, 100000, 100000, 100000]
#    restart_weights: [1, 0.5, 0.5, 0.5]
#    eta_min: !!float 1e-6
    type: MultiStepLR
    milestones: [150000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  infonce_opt:
    type: InfoNCELoss
    loss_weight: 1.0
    temperature: 0.1
    negative_mode: unpaired
    reduction: mean

### validation settings
val:
  val_freq: !!float 1e4
  save_img:
    enable: true
    save_label: true
    save_pdwimg: false
    save_featureTSNE: true

  metrics:
    ac: # metric name, can be arbitrary
      type: calculate_ac
    nmi:
      type: calculate_nmi
    ari:
      type: calculate_ari

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
