# Modified SRResNet w/o BN from:
# Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network
# Use perceptual loss before ReLU as ESRGAN does

# general settings
name: 004_Deinterleaving_Reformer_CL_2to10_2k_allNeg
model_type: CLModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: JHT2025Pre_mix2to10
    type: DeinterleavingDataset
    dataroot: F:/Datasets/JHT2025Pre/train1015
    filename_tmpl: '{}'
    io_backend:
      type: disk


    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: JHT2025Pre_mix2to10
    type: DeinterleavingDataset
    dataroot: F:/Datasets/JHT2025Pre/val1015
    io_backend:
      type: disk

# network structures
network_g:
  type: Reformer
  seq_len: 2000
  enc_in: 5
  d_model: 128
  c_out: 32
  n_heads: 8
  d_ff: 512
  activation: relu
  dropout: 0.1
  e_layers: 8
  bucket_size: 8
  n_hashes: 8

network_d:
  type: SimpleMLP
  seq_len: 3000
  c_in: 32
  c_out: 10
  d_model: 128

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: !!float 1e-5
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000, 100000, 100000, 100000]
    restart_weights: [1, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-6

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  infonce_opt:
    type: InfoNCELoss
    loss_weight: 1.0
    negative_mode: paired
    reduction: mean
  seqce_opt:
    type: SeqCELoss
    loss_weight: !!float 1e-3
    reduction: mean
### validation settings
val:
  val_freq: !!float 1e4
  save_img:
    enable: true
    save_label: true
    save_pdwimg: false
    save_featureTSNE: true

  metrics:
    ac: # metric name, can be arbitrary
      type: calculate_ac
    nmi:
      type: calculate_nmi
    ari:
      type: calculate_ari

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
